import Head from "next/head";
import "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center color">
      <h1>League Of Stones</h1>
      <nav>
      <ul>
        <Link href={"./signin"}>Connexion</Link>
        <Link href={"./inscription"}>Inscription</Link>
        <Link href={"./game/prototype"}>Jouer</Link>
      </ul>
      </nav>
      </div>

    </>
  );
}
